# Generated by Django 5.1.4 on 2025-01-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='servings_unit',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time_unit',
            field=models.CharField(default='', max_length=20),
        ),
    ]
